name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      #
      # - run: npm ci
      #
      # - run: npm run build --if-present
      #
      # - run: npm run test --if-present

      - name: event diagnotics
        run: |
          echo event name: ${{ toJson(github.event_name) }}
          echo event type: ${{ toJson(github.event.action) }}
          echo actor: ${{ toJson(github.actor) }}
          echo === event begin ===
          cat <<EOF
          ${{ toJson(github.event) }}
          EOF
          echo === event end ===

      - name: PR message...
        run: |
          cat <<EOF
          TITLE: ${{ toJson(github.event.pull_request.title) }}
          BODY:  ${{ toJson(github.event.pull_request.body) }}
          EOF

      - name: try to get commits
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            //console.dir(context);
            const result = await github.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              per_page: 250,
            });
            //console.dir(result.data);
            const commits = result.data.map(c => c.commit);
            console.dir(commits);

      # - name: pretend publish - ${{github.event.release.name}} (${{github.event.release.tag_name}})
      #   run: |
      #     git config user.email release-bot@noreply.foopy.com
      #     git config user.name Release Bot
      #     npm version ${{github.event.release.tag_name}}
      #     git status
      #     #git graph -4
      #     git log -4
      #     git push
